<#
.SYNOPSIS
Read-only audit of an old Windows user profile and system dependencies.

Designed to answer: "Can I safely delete this profile?"
#>

param(
    [string]$UserName = "JerryAdmin",
    [string]$ProfilePath = "C:\Users\JerryAdmin",
    [switch]$SkipExternalOwnership
)

$ErrorActionPreference = "Stop"

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$Report = Join-Path $PWD "UserProfileAudit-$($UserName)-$stamp.txt"

# Initialize report file
"" | Out-File -FilePath $Report -Encoding utf8

function Write-ReportLine {
    param(
        [string]$Text = "",
        [ValidateSet('Info','Pass','Warning','Action','Header')]
        [string]$Level = 'Info',
        
        # Defer remediation logic to a separate pipeline by 
        # capturing the raw data targets here.
        [string]$RemediationType = "",
        [string]$RemediationTarget = "",
        
        # Output format toggle
        [switch]$AsHtml
    )

    # 1. Console Colorization
    $color = switch ($Level) {
        'Pass'    { 'Green' }
        'Warning' { 'Yellow' }
        'Action'  { 'Red' }
        'Header'  { 'Cyan' }
        default   { 'White' }
    }

    Write-Host $Text -ForegroundColor $color

    # 2. File Output Formatting
    if ($AsHtml) {
        $class = $Level.ToLower()
        # Encode basic HTML to prevent rendering issues
        $safeText = $Text -replace '&','&amp;' -replace '<','&lt;'
        
        $line = "<div class='log-$class'>$safeText</div>"
        
        # Embed remediation data invisibly for later parsing
        if ($RemediationTarget) {
            $line += "<div class='remediation-data' " + 
                     "data-type='$RemediationType' " +
                     "data-target='$RemediationTarget' " +
                     "style='display:none;'></div>"
        }
        
        $line | Out-File -FilePath $Report -Encoding utf8 -Append
    } else {
        $Text | Out-File -FilePath $Report -Encoding utf8 -Append
        
        # Append plain text metadata for downstream regex scraping
        if ($RemediationTarget) {
            "  [DATA] TYPE: $RemediationType | " + 
            "TARGET: $RemediationTarget" | 
              Out-File -FilePath $Report -Encoding utf8 -Append
        }
    }
}

function Section {
    param([string]$Name)
    Write-ReportLine ""
    Write-ReportLine ("=" * 72)
    Write-ReportLine $Name
    Write-ReportLine ("=" * 72)
}

function Safe {
    param(
        [scriptblock]$Body,
        [string]$Context
    )
    try {
        & $Body
        $true
    }
    catch {
        Write-ReportLine "[WARNING] ${Context}: $_"
        $false
    }
}

# Admin check
if (-not ([Security.Principal.WindowsPrincipal] `
    [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(`
    [Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-ReportLine "[ERROR] This script must be run as Administrator."
    exit 1
}

Section "Profile"

Write-ReportLine "User    : $UserName"
Write-ReportLine "Profile : $ProfilePath"

if (Test-Path $ProfilePath){
    $size = (Get-ChildItem `
      $ProfilePath -Force -Recurse -File -ErrorAction SilentlyContinue |
      Measure-Object Length -Sum).Sum
    Write-ReportLine ("Size    : {0:N2} GB" -f ($size/1GB))
} else {
    Write-ReportLine "Profile directory not found."
}

Section "Interesting directories"

@(
    ".ssh",
    ".gnupg",
    "Documents\WindowsPowerShell",
    "Documents\PowerShell",
    "AppData\Local\Programs",
    "AppData\Microsoft\Windows\Start Menu\Programs\Startup"
) | ForEach-Object{
    $p=Join-Path $ProfilePath $_
    Write-ReportLine ("{0,-55} {1}" -f $_,(Test-Path $p))
}

Section "Executable content"

# NOISE FILTER EXPLANATIONS:
#
# 1. AppData\Local\Temp & \Temp\: Ephemeral cache files, auto-generated
#    installers, and installer stubs. Not permanent user scripts.
#
# 2. AppData\Local\Packages: UWP App Sandbox folders (e.g., Microsoft
#    Edge, Store Apps). Generated by Windows, not human user scripts.
#
# 3. AppData\Local\Microsoft\Windows\INetCache: Browser cache
#    binaries/scripts downloaded while browsing.
#
# 4. \node_modules\ & \.git\: Developer dependency trees/repositories
#    containing thousands of third-party CLI scripts/binaries.

$null = Safe {
    $excludePatterns = `
      '\\(Temp|AppData\\Local\\Temp|' `
      + 'AppData\\Local\\Packages|' `
      + 'AppData\\Local\\Microsoft\\Windows\\INetCache|' `
      + '\.git|node_modules)\\'

    $foundExecutables = Get-ChildItem $ProfilePath -Recurse `
      -Force -ErrorAction SilentlyContinue `
      -Include *.exe,*.cmd,*.bat,*.ps1,*.vbs,*.lnk |
      Where-Object { $_.FullName -notmatch $excludePatterns }

    if ($foundExecutables) {
        # Group by extension and take up to 50 per file type to avoid
        # one noisy file type dominating
        $foundExecutables | Group-Object Extension | 
          ForEach-Object {
            Write-ReportLine `
              "-- Extension: $($_.Name) (First 50 of $($_.Count)) --"
              $_.Group | Select-Object -First 50 | ForEach-Object {
                  Write-ReportLine ("  {0}" -f $_.FullName)
              }
          }
    } else {
        Write-ReportLine "No executable binaries or scripts " +
        "found outside excluded temp/cache paths."
    }
} "Searching profile executable content"

Section "HKCU audit"

$tempHive="HKU\OLDPROFILEAUDIT"
$nt=Join-Path $ProfilePath "NTUSER.DAT"

if (Test-Path $nt){
    $loaded = Safe {
        & reg.exe load $tempHive $nt | Out-Null
        if ($LASTEXITCODE -ne 0) {
            throw "reg.exe load failed with exit code $LASTEXITCODE"
        }
    } "Loading NTUSER.DAT"

    if ($loaded){
        try {
            $null = Safe {
                Write-ReportLine "-- Uninstall entries --"

                $k = "Registry::$tempHive" + `
                  '\Software\Microsoft\Windows\CurrentVersion\Uninstall'
                
                if (Test-Path $k){
                    Get-ChildItem $k | ForEach-Object{
                        $p=Get-ItemProperty $_.PSPath
                        if ($p.DisplayName){
                            Write-ReportLine (
				"  {0} | {1} | {2}" -f 
				$p.DisplayName, $p.DisplayVersion, 
				$p.Publisher)
                        }
                    }
                }
            } "Reading uninstall keys"

            $null = Safe {
                foreach($r in
                "Software\Microsoft\Windows\CurrentVersion\Run",
                "Software\Microsoft\Windows\CurrentVersion\RunOnce"){
                    $k="Registry::$tempHive\$r"
                    Write-ReportLine "-- $r --"
                    if (Test-Path $k){
                        (Get-ItemProperty $k).PSObject.Properties |
                        Where-Object Name -notmatch '^PS' |
                        ForEach-Object{
                            Write-ReportLine ("  {0} = {1}" -f `
                                              $_.Name, $_.Value)
                        }
                    }
                }
            } "Reading Run keys"
        }
        finally {
            # Guaranteed registry unmount regardless of exceptions
            # during read operations
            $null = Safe {
                & reg.exe unload $tempHive *> $null
            } "Unloading hive"
        }
    }
}

Section "Machine-Wide Uninstall Entries"

$null = Safe {
    Write-ReportLine "Scanning HKLM Uninstall keys for old profile paths..."
    
    $uninstallPaths = @(
        "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall",
        "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\" + `
          "CurrentVersion\Uninstall"
    )

    $foundAny = $false

    foreach ($path in $uninstallPaths) {
        if (Test-Path $path) {
            Get-ChildItem $path -ErrorAction SilentlyContinue | 
              ForEach-Object {
                $prop = Get-ItemProperty $_.PSPath
                
                $isOrphan = $false
                # Check the three standard properties that point to files
                foreach ($val in @($prop.InstallLocation, 
                                   $prop.UninstallString, 
                                   $prop.QuietUninstallString)) {
                    if ($val -match [regex]::Escape($ProfilePath)) {
                        $isOrphan = $true
                    }
                }

                if ($isOrphan) {
                    $foundAny = $true
                    # Fallback to the registry key name if DisplayName 
                    # is missing
                    $name = if ($prop.DisplayName) { $prop.DisplayName } 
                            else { $_.PSChildName }
                    
                    Write-ReportLine -Text ("  {0} | {1}" -f `
                                      $name, $prop.DisplayVersion) `
                                     -Level Warning `
                                     -RemediationType "HKLMUninstall" `
                                     -RemediationTarget $_.PSPath
                }
            }
        }
    }

    if (-not $foundAny) {
        Write-ReportLine -Text "  No orphaned machine-wide uninstallers." `
                         -Level Pass
    }
} "Auditing HKLM Uninstall keys"

Section "Machine-Wide References"

$null = Safe {
    # Test for Sysinternals Autorunsc (command-line autoruns)
    $autorunsc = Get-Command "autorunsc.exe" `
      -ErrorAction SilentlyContinue
    
    if (-not $autorunsc) {
        Write-ReportLine "[ERROR] Sysinternals 'autorunsc.exe' missing."
        Write-ReportLine "Cannot perform deep machine-wide audit."
        Write-ReportLine "1. Download Sysinternals Autoruns from:"
        Write-ReportLine "   https://learn.microsoft.com/en-us/" + `
                         "sysinternals/downloads/autoruns"
        Write-ReportLine "2. Place autorunsc.exe in System PATH."
        Write-ReportLine "3. Or install via winget:"
        Write-ReportLine "   winget install Sysinternals.Autoruns"
        throw "autorunsc.exe not found. Halting this section."
    }

    Write-ReportLine "Scanning auto-starts via autorunsc.exe..."
    # -a *: all entries, -c: CSV output, -nobanner: suppress header
    $csvOutput = & $autorunsc.Source -a * -c -nobanner 2> $null
    $csv = $csvOutput | ConvertFrom-Csv -ErrorAction SilentlyContinue

    if ($csv) {
        $orphans = $csv | Where-Object {
            $isMatch = $false
            # Check every column dynamically in case schema changes
            $_.PSObject.Properties | ForEach-Object {
                if ($_.Value -match [regex]::Escape($ProfilePath)) {
                    $isMatch = $true
                }
            }
            $isMatch
        }

        if ($orphans) {
            $orphans | ForEach-Object {
                Write-ReportLine ("  Location: {0}" -f $_.Location)
                Write-ReportLine ("  Entry   : {0}" -f $_.Entry)
                Write-ReportLine ("  Path    : {0}" -f $_."Image Path")
                Write-ReportLine ("  " + "-" * 68)
            }
        } else {
            Write-ReportLine "  No machine-wide auto-starts found."
        }
    }

    Write-ReportLine ""
    Write-ReportLine "Scanning HKLM for literal string matches..."
    # Using native reg.exe. RegScanner CLI requires a binary/ini .cfg
    # file to run silently, which reduces script portability.
    foreach ($hive in @("HKLM\SOFTWARE", "HKLM\SYSTEM")) {
        $reg = & reg.exe query $hive /f $ProfilePath /s /d 2> $null
        if ($LASTEXITCODE -eq 0 -and $reg) {
            $reg | Where-Object { $_ -match 'HKEY_LOCAL_MACHINE' } |
            Select-Object -First 20 | ForEach-Object {
                Write-ReportLine ("  {0}" -f $_.Trim())
            }
        } else {
            Write-ReportLine "  No matches found in $hive."
        }
    }
} "Auditing machine-wide references"

Section "Scheduled Tasks"

$null = Safe {
    # Resolve the username to a Security Identifier (SID)
    $userSid = $null
    try {
        $ntAccount = New-Object `
          System.Security.Principal.NTAccount($UserName)
        $userSid = $ntAccount.Translate(
          [System.Security.Principal.SecurityIdentifier]).Value
    } catch {
        Write-ReportLine -Text "[WARNING] Could not resolve SID for $UserName" `
                         -Level Warning
    }

    Get-ScheduledTask |
    Where-Object {
        $isPrincipalMatch = ($_.Principal.UserId -match `
          [regex]::Escape($UserName))
        
        $isSidMatch = ($userSid -and `
          ($_.Principal.UserId -eq $userSid))
        
        $isActionMatch = $false
        if ($_.Actions) {
            foreach ($action in $_.Actions) {
                # Check both Execute path and command Arguments
                if (($action.Execute -match `
                      [regex]::Escape($ProfilePath)) -or
                    ($action.Arguments -match `
                      [regex]::Escape($ProfilePath))) {
                    $isActionMatch = $true
                }
            }
        }
        
        $isPrincipalMatch -or $isSidMatch -or $isActionMatch
    } |
    ForEach-Object {
        $msg = "{0} -> {1}" -f $_.TaskPath, $_.TaskName
        Write-ReportLine -Text $msg `
                         -Level Warning `
                         -RemediationType "ScheduledTask" `
                         -RemediationTarget "$($_.TaskPath)$($_.TaskName)"
    }
} "Scheduled tasks"

Section "Services"

$null = Safe {
    Get-CimInstance Win32_Service |
    Where-Object{
        $_.StartName -match [regex]::Escape($UserName)
    } |
    ForEach-Object{
        Write-ReportLine ("{0} ({1})" -f $_.Name,$_.StartName)
    }
} "Services"

Section "External System File Ownership Audit"

$null = Safe {
    $accessChkCmd = `
      Get-Command "accesschk.exe" -ErrorAction SilentlyContinue

    if ($accessChkCmd) {
        Write-ReportLine "Sysinternals AccessChk scan " +
        "for files owned by '$UserName'..."
        
        $targetSystemPaths = @(
            "C:\ProgramData",
            "C:\Program Files",
            "C:\Program Files (x86)",
            "C:\Windows\System32\Tasks",
            "C:\Drivers",
            "C:\Tools",
            "C:\Scripts"
        )

        foreach ($sysPath in $targetSystemPaths) {
            if (Test-Path $sysPath) {
                Write-ReportLine "-- Ownership Audit: $sysPath --"
                # -q: suppress banner, -s: recurse, -o: filter by owner
                & accesschk.exe -q -s -o $UserName $sysPath |
                  ForEach-Object {
                      Write-ReportLine ("  {0}" -f $_)
                }
            }
        }
    } else {
        Write-ReportLine "[NOTICE] 'accesschk.exe' was not found in System PATH or working directory."
        Write-ReportLine "External file ownership audit was skipped."
        Write-ReportLine ""
        Write-ReportLine "To perform external file ownership checks:"
        Write-ReportLine "1. Download Sysinternals AccessChk from: https://learn.microsoft.com/en-us/sysinternals/downloads/accesschk"
        Write-ReportLine "2. Place 'accesschk.exe' in this directory or in C:\Windows\System32."
        Write-ReportLine "3. Alternatively, install via winget: 'winget install Sysinternals.AccessChk'"
    }
} "Auditing external file ownership"

Section "Summary"

Write-ReportLine "If the sections above are essentially empty, there is little evidence"
Write-ReportLine "that deleting this profile will break software or orphan system file ownership."

Write-Host ""
Write-Host "Report written to $Report"
